apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python app that displays time - named ${{values.app_name}}
  annotations:
    github.com/project-slug: aum-thakkar/${{values.app_name}}
    backstage.io/techdocs-ref: dir:. # (<-- This one is for Techdocs) 
 
spec:
  type: service
  owner: development
  lifecycle: experimental